Add Discord UI Buttons to Verify Error + Ban Approval
hackthebox/Hackster pull request #52
Opened 2023-06-06 15:44 UTC by 0xEmma

## Types of changes

What types of changes does your code introduce?
*Put an `x` in the boxes that apply.*

- [ ] Bugfix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected).
- [ ] Documentation Update (if none of the other choices applies).

## Proposed changes

Discord native buttons! No more running commands when you can just hit it

## Checklist

*Put an `x` in the boxes that apply.*

- [ ] I have read and followed the [CONTRIBUTING.md](https://github.com/hackthebox/Hackster/blob/main/CONTRIBUTING.md)
  doc.
- [ ] Lint and unit tests pass locally with my changes.
- [ ] I have added the necessary documentation (if appropriate).

## Additional context

Add any other context or screenshots here.

2023-06-19 11:57 UTC, dimoschi requested changes
The PR is in the right direction, however the `helpers.ban.ban_member` already sends a message to the `SR_MOD` channel if approval is required, so maybe the Approve/Deny buttons should be added there.

2023-06-20 13:12 UTC, 0xEmma commented
> 

Will make that change

2023-06-20 13:15 UTC, 0xEmma commented
The code already sends it in the ban_member class, its just defined in the ban cog

2024-03-28 09:21 UTC, dimoschi requested changes
Many changes are required for this PR to work.

2024-03-28 09:21 UTC, dimoschi commented on src/cmds/core/ban.py
> +    class BanApprove(discord.ui.view):
`discord.ui.view` is not a class, so you cannot extend. Maybe you wanted to write `discord.ui.view.View`. In that case better import it `from discord.ui.view import View` and use it.

2024-03-28 09:21 UTC, dimoschi commented on src/cmds/core/ban.py
> +    class BanApprove(discord.ui.view):
Also, why BanApprove is a nested class? This is uncommon pattern in Python.

2024-03-28 09:21 UTC, dimoschi commented on src/cmds/core/ban.py
> +        def __init__(self, ban_id):
Please add type annotation for `ban_id`

2024-03-28 09:21 UTC, dimoschi commented on src/cmds/core/ban.py
> +            member = await self.bot.get_member_or_user(interaction.guild, ban.user_id)
Here `self` refers to the instance of the class `BanApprove`, which doesn't have access to `bot` member that exists in "parent class" `BanCog`

2024-03-28 09:21 UTC, dimoschi commented on src/cmds/core/ban.py
> +            self.bot.loop.create_task(
Same as above `BanApprove` doesn't have access to `bot`

2024-03-28 09:21 UTC, dimoschi commented on src/cmds/core/ban.py
> +        async def deny_ban(self, interaction: discord.Interaction, button: discord.ui.Button):
The `button` argument is not used, maybe remove it?

2024-03-28 09:21 UTC, dimoschi commented on src/cmds/core/ban.py
> +        async def approve_ban(self, interaction: discord.Interaction, button: discord.ui.Button):
The `button` argument is not used, maybe remove it?

2024-03-28 09:21 UTC, dimoschi commented on src/cmds/core/identify.py
> +        async def remove_Token(self, interaction: discord.Interaction, button: discord.ui.Button):
Function names should be all lowercase.

2024-03-28 09:21 UTC, dimoschi commented on src/cmds/core/identify.py
> +        async def remove_Token(self, interaction: discord.Interaction, button: discord.ui.Button):
Also, `button` is not being used.

2024-03-28 09:21 UTC, dimoschi commented on src/cmds/core/identify.py
> +    class VerifyError(discord.ui.view):
`discord.ui.view` is not a class, so you cannot extend. Maybe you wanted to write `discord.ui.view.View`. In that case better import it `from discord.ui.view import View` and use it.

2024-04-01 04:03 UTC, closed without merging