Manual Cert Validation
hackthebox/Hackster pull request #66
Opened 2023-09-12 19:59 UTC by 0xEmma

## Types of changes

What types of changes does your code introduce?
*Put an `x` in the boxes that apply.*

- [ ] Bugfix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected).
- [ ] Documentation Update (if none of the other choices applies).

## Proposed changes
Add manual certification validation

## Checklist

*Put an `x` in the boxes that apply.*

- [ ] I have read and followed the [CONTRIBUTING.md](https://github.com/hackthebox/Hackster/blob/main/CONTRIBUTING.md)
  doc.
- [ ] Lint and unit tests pass locally with my changes.
- [ ] I have added the necessary documentation (if appropriate).

## Additional context

Add any other context or screenshots here.

2023-11-07 08:59 UTC, dimoschi requested changes
Looks good, a minor fix is needed.

2023-11-07 08:59 UTC, dimoschi commented on src/helpers/verification.py
> +    cert_api_url = f"{settings.API_V4_URL}certificate/lookup"
There is a `/` missing

```suggestion
    cert_api_url = f"{settings.API_V4_URL}/certificate/lookup"
```

2023-11-07 10:33 UTC, 0xEmma commented
Resolved @dimoschi

2023-11-07 10:39 UTC, dimoschi approved these changes
LGTM

2023-11-08 17:59 UTC, dimoschi approved these changes

2023-11-08 17:59 UTC, merged